pipeline {
    agent any

    environment {
        IMAGE_NAME = "ananyahkp/flask-devops-app"   // Docker Hub username + repo
        IMAGE_TAG  = "latest"
        DOCKER_CREDS = credentials('dockerhub-creds') // Jenkins Docker Hub credential
    }

    stages {

        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/ananyahkp10/flask-devops-project.git', branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $IMAGE_NAME:$IMAGE_TAG -f docker/Dockerfile ."
            }
        }

        stage('Run Unit Test') {
            steps {
                // Run the test inside the Docker image
                sh "docker run --rm $IMAGE_NAME:$IMAGE_TAG python -m pytest test_app.py"
            }
        }

        stage('Login & Push Docker Image') {
            steps {
                // Use Jenkins credentials to login to Docker Hub
                sh """
                echo \$DOCKER_CREDS_PSW | docker login -u \$DOCKER_CREDS_USR --password-stdin
                docker push $IMAGE_NAME:$IMAGE_TAG
                """
            }
        }

        stage('Deploy Locally') {
            steps {
                // Stop existing container if running, remove it, and deploy a new one
                sh """
                docker stop flaskapp || true
                docker rm flaskapp || true
                docker run -d --restart=always -p 80:80 --name flaskapp $IMAGE_NAME:$IMAGE_TAG
                """
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully!"
        }
        failure {
            echo "❌ Pipeline failed!"
        }
    }
}

